//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basicForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_descruption { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string user_gender { get; set; }
        public Nullable<bool> user_is_intrested_inJava { get; set; }
        public Nullable<bool> user_is_intrested_cSharp { get; set; }
        public Nullable<bool> use_is_intrested_pythod { get; set; }
        public Nullable<int> user_country_id { get; set; }
        public string user_city { get; set; }
    
        public virtual country country { get; set; }

        public MyCity CityList { get; set; }
    }
}
public enum MyCity
{
    Ghatkopar,
    Vikroli,
    Thane
}
